### ISSUE TITLE
Exception thrown when logging out

### ISSUE THREAD

**Issue by giano574** [aau-giraf/weekplanner-OLDUI#319]
**Describe the bug**
When logging out, `setState()` or `markNeedsBuild()` is called during build, which throws an exception. Seems to be caused by using a wrong context. 
Also see bug report https://github.com/aau-giraf/weekplanner/issues/185.

**To Reproduce**
1. Start app.
2. Log in.
3. Press log out icon.
4. Press 'Log ud'.

**Expected behavior**
No exceptions should be thrown.

**Actual behavior**
Manual 'stack trace':
```
#1 _authBlock.logout()                                      lib/blocs/toolbar_bloc.dart:334
#2 _api.account.logout()                                    lib/blocs/auth_bloc.dart:64
#3 _api.account.logout().listen()                           lib/blocs/auth_bloc.dart:64
#4 _loggedIn.add(false)                                     lib/blocs/auth_bloc.dart:65
#5 Routes.goHome(context)                                   lib/main.dart:52
#6 Navigator.of(context).popUntil((Route<dynamic> route)    lib/routes.dart:21
```

<details>
<summary>Exception caught by animation library</summary>

```
════════ Exception caught by animation library ═════════════════════════════════
The following assertion was thrown while notifying status listeners for AnimationController:
setState() or markNeedsBuild() called during build.

This _ModalScope<Center> widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: _ModalScope<Center>-[LabeledGlobalKey<_ModalScopeState<Center>>#4e5f0]
    state: _ModalScopeState<Center>#5c0d1
The widget which was currently being built when the offending call was made was: StreamBuilder<bool>
    dirty
    state: _StreamBuilderBaseState<bool, AsyncSnapshot<bool>>#9b86b
When the exception was thrown, this was the stack
#0      Element.markNeedsBuild.<anonymous closure> 
package:flutter/…/widgets/framework.dart:3896
#1      Element.markNeedsBuild 
package:flutter/…/widgets/framework.dart:3911
#2      State.setState 
package:flutter/…/widgets/framework.dart:1168
#3      _ModalScopeState._routeSetState 
package:flutter/…/widgets/routes.dart:664
#4      ModalRoute.setState 
package:flutter/…/widgets/routes.dart:784
...
The AnimationController notifying status listeners was: AnimationController#19fed(◀ 1.000; for _DialogRoute<Center>)
```
</details>

**Screenshots**
N/A.

**Environment**
N/A.

**Additional context**
N/A.

**Comment by EsbenNedergaard** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write tests for #319 (logout)](https://trello.com/c/twXciYvQ/11-write-tests-for-319-logout)

**Comment by Rsvend17** [comment]
Issue seems to still be open, even though a linked pull request was merged, and closed.
